project_id = "oevwcgemxfoekoemcykx"

[auth]
site_url = "http://172.31.144.1:8080"
additional_redirect_urls = ["http://127.0.0.1:8080", "http://localhost:8080", "http://172.31.144.1:8080"]

[functions.validate-family-access]
verify_jwt = false

# Configurações de segurança para Edge Functions
[functions.validate-family-access.env]
ALLOWED_ORIGINS = "http://localhost:8080,http://127.0.0.1:8080,https://pei-collab.vercel.app,https://pei-collab.netlify.app"
RATE_LIMIT_RECENT_MINUTES = "15"
RATE_LIMIT_RECENT_ATTEMPTS = "3"
RATE_LIMIT_HOURLY_ATTEMPTS = "10"
LOG_LEVEL = "info"