// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@pei/database';

// Valores padrão: Supabase online (produção) - mesmo que pei-collab
const DEFAULT_SUPABASE_URL = 'https://fximylewmvsllkdczovj.supabase.co';
const DEFAULT_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4aW15bGV3bXZzbGxrZGN6b3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2OTY0NzIsImV4cCI6MjA3NzI3MjQ3Mn0.3FqQqUfVgD3hIh1daa3R1JjouGZ4D4ONR6SmcL9Qids';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || DEFAULT_SUPABASE_ANON_KEY;

// 🔒 VALIDAÇÃO DE SEGURANÇA: Prevenir uso de chave demo em produção
if (import.meta.env.PROD && SUPABASE_PUBLISHABLE_KEY.includes('supabase-demo')) {
  throw new Error(
    '🚨 ERRO DE SEGURANÇA: Chave demo do Supabase detectada em produção! ' +
    'Configure a variável VITE_SUPABASE_ANON_KEY com a chave real do projeto.'
  );
}

// Validar que as variáveis necessárias estão configuradas em produção
if (import.meta.env.PROD && (!SUPABASE_URL || SUPABASE_URL.includes('127.0.0.1') || SUPABASE_URL.includes('localhost'))) {
  throw new Error(
    '🚨 ERRO DE CONFIGURAÇÃO: URL do Supabase não configurada para produção! ' +
    'Configure a variável VITE_SUPABASE_URL.'
  );
}

// Log apenas em desenvolvimento para debug
if (import.meta.env.DEV) {
  if (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_ANON_KEY) {
    console.warn('⚠️ Variáveis de ambiente VITE_SUPABASE_URL ou VITE_SUPABASE_ANON_KEY não encontradas. Usando valores padrão (Supabase online).');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Evita problemas com bloqueadores
    flowType: 'pkce', // Usa PKCE flow (mais seguro e funciona melhor com bloqueadores)
  },
  db: {
    schema: 'public',
  },
});

export type { Database };

