// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'http://127.0.0.1:54321';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0';

// 🔒 VALIDAÇÃO DE SEGURANÇA: Prevenir uso de chave demo em produção
if (import.meta.env.PROD && SUPABASE_PUBLISHABLE_KEY.includes('supabase-demo')) {
  throw new Error(
    '🚨 ERRO DE SEGURANÇA: Chave demo do Supabase detectada em produção! ' +
    'Configure a variável VITE_SUPABASE_ANON_KEY com a chave real do projeto.'
  );
}

// Validar que as variáveis necessárias estão configuradas em produção
if (import.meta.env.PROD && (!SUPABASE_URL || SUPABASE_URL.includes('127.0.0.1') || SUPABASE_URL.includes('localhost'))) {
  throw new Error(
    '🚨 ERRO DE CONFIGURAÇÃO: URL do Supabase não configurada para produção! ' +
    'Configure a variável VITE_SUPABASE_URL.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Evita problemas com bloqueadores
    flowType: 'pkce', // Usa PKCE flow (mais seguro e funciona melhor com bloqueadores)
  },
  db: {
    schema: 'public',
  },
  global: {
    headers: {
      'x-client-info': 'pei-collab@1.0.0',
    },
  },
  // Otimizações para reduzir requisições desnecessárias
  realtime: {
    params: {
      eventsPerSecond: 10, // Limita eventos por segundo
    },
  },
});